version: '2'
services:
  mongo:
    image: mongo
    command: mongod --smallfiles --oplogSize 128 --replSet "rs0"
  rocketchat:
    image: rocketchat/rocket.chat
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongo:27017/rocketchat
      - MONGO_OPLOG_URL=mongodb://mongo:27017/local
    ports:
      - "3000:3000"
