# On souhaite utiliser l'image de base Apache2
FROM httpd:2.4
# La personne en charge de la maintenance
MAINTAINER Thomas SARBONI <max-k@post.com>
# On copie nos sources dans ce répertoire
ADD htdocs/ /usr/local/apache2/htdocs/
